In [1]:
import openpyxl
from openpyxl import load_workbook
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from mpl_toolkits.mplot3d import Axes3D
%matplotlib notebook
np.set_printoptions(suppress=True)

In [2]:
df = pd.read_excel("dataset.xlsx", sheet_name=None, header=0)

# Section 4.1-(2) Table 4.1.2, Table 4.1.3, Table 4.1.4

In [3]:
all_df = {}
for i, d in enumerate(df.items()):
    name, data = d
    all_df[name] = data

In [4]:
data = all_df['1K-01']
#data_test = all_df['1X-02']

In [5]:
data = data[data['DEPTH'] == data["DEPTH"]]   # drop NaN value row
#data_test = data_test[data_test['DEPTH'] == data_test["DEPTH"]]   # drop NaN value row

In [6]:
data = data.drop(["Core_Facies"], axis=1)
#data_test = data_test.drop(["Core_Facies"], axis=1)

In [7]:
data['Log_Facies'].apply(lambda x: str(x)).describe()

count     1025
unique       3
top        1.0
freq       530
Name: Log_Facies, dtype: object

## Table 4.1.2

In [8]:
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LogisticRegression

In [9]:
X = data[["DEPTH", "CALI", "DT", "GR", "LLD", "LLS", "MSFL", "NPHI", "RHOB"]]
ss = StandardScaler()
X = ss.fit_transform(X)
X_real = data[["DEPTH", "CALI", "DT", "GR", "LLD", "LLS", "MSFL", "NPHI", "RHOB"]]

In [10]:
Y = data['Log_Facies'].apply(lambda x: int(x)-1)
#Y_test = data_test['Log_Facies'].apply(lambda x: int(x)-1)

In [11]:
clf = LogisticRegression()
clf_real = LogisticRegression()

In [12]:
clf.fit(X, Y)
clf_real.fit(X_real, Y)

/anaconda3/lib/python3.7/site-packages/sklearn/linear_model/logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
/anaconda3/lib/python3.7/site-packages/sklearn/linear_model/logistic.py:460: FutureWarning: Default multi_class will be changed to 'auto' in 0.22. Specify the multi_class option to silence this warning.
  "this warning.", FutureWarning)
/anaconda3/lib/python3.7/site-packages/sklearn/linear_model/logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
/anaconda3/lib/python3.7/site-packages/sklearn/linear_model/logistic.py:460: FutureWarning: Default multi_class will be changed to 'auto' in 0.22. Specify the multi_class option to silence this warning.
  "this warning.", FutureWarning)


LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='warn',
          n_jobs=None, penalty='l2', random_state=None, solver='warn',
          tol=0.0001, verbose=0, warm_start=False)

In [13]:
#Y_pred = clf.predict(X)
#Y_real_pred = clf.predict(X_real)

In [14]:
print(clf.intercept_)
print(clf.coef_)

[-0.23088812 -0.38637902 -5.331887  ]
[[ 0.06540731 -0.20490059 -0.99202325  0.27874922  1.01387764 -1.51442859
   1.15717478 -1.24748841 -3.56451337]
 [ 1.13719754 -0.03029435  0.6867362   0.05459472  0.9444873  -0.12385016
  -0.68960912  0.41124826  1.68873727]
 [-3.2547469   1.09666476  0.09938329  0.08917029 -1.33224463  0.83745061
   0.0253272   0.24571485  1.03975919]]


In [15]:
coef = np.round(clf.coef_, 4)
print(coef)
coef = abs(coef)
coef = np.sum(coef, axis=0)
coef

[[ 0.0654 -0.2049 -0.992   0.2787  1.0139 -1.5144  1.1572 -1.2475 -3.5645]
 [ 1.1372 -0.0303  0.6867  0.0546  0.9445 -0.1239 -0.6896  0.4112  1.6887]
 [-3.2547  1.0967  0.0994  0.0892 -1.3322  0.8375  0.0253  0.2457  1.0398]]


array([4.4573, 1.3319, 1.7781, 0.4225, 3.2906, 2.4758, 1.8721, 1.9044,
       6.293 ])


## Table 4.1.3

In [16]:
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LogisticRegression

In [17]:
X = data[[ "DT", "GR", "LLD","LLS", "MSFL", "NPHI", "RHOB"]]
ss = StandardScaler()
X = ss.fit_transform(X)
X_real = data[["DT", "GR", "LLD","LLS", "MSFL", "NPHI", "RHOB"]]

In [18]:
Y = data['Log_Facies'].apply(lambda x: int(x)-1)
#Y_test = data_test['Log_Facies'].apply(lambda x: int(x)-1)

In [19]:
clf = LogisticRegression()
clf_real = LogisticRegression()

In [20]:
clf.fit(X, Y)
clf_real.fit(X_real, Y)

/anaconda3/lib/python3.7/site-packages/sklearn/linear_model/logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
/anaconda3/lib/python3.7/site-packages/sklearn/linear_model/logistic.py:460: FutureWarning: Default multi_class will be changed to 'auto' in 0.22. Specify the multi_class option to silence this warning.
  "this warning.", FutureWarning)
/anaconda3/lib/python3.7/site-packages/sklearn/linear_model/logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
/anaconda3/lib/python3.7/site-packages/sklearn/linear_model/logistic.py:460: FutureWarning: Default multi_class will be changed to 'auto' in 0.22. Specify the multi_class option to silence this warning.
  "this warning.", FutureWarning)


LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='warn',
          n_jobs=None, penalty='l2', random_state=None, solver='warn',
          tol=0.0001, verbose=0, warm_start=False)

In [21]:
print(clf.intercept_)
print(clf.coef_)

[-0.22783051 -0.41209408 -4.53286501]
[[-0.95829021  0.2872702   1.12666978 -1.62000297  1.13446117 -1.30221804
  -3.62549668]
 [ 0.80854672 -0.41603878  0.45493568 -0.27942103 -0.71765968  0.19142153
   1.85087969]
 [-0.4264523   1.21169528 -2.10329285  2.80897558  0.00158792  0.65662783
   0.92056878]]


In [22]:
coef = np.round(clf.coef_, 4)
print(coef)
coef = abs(coef)
coef = np.sum(coef, axis=0)
coef

[[-0.9583  0.2873  1.1267 -1.62    1.1345 -1.3022 -3.6255]
 [ 0.8085 -0.416   0.4549 -0.2794 -0.7177  0.1914  1.8509]
 [-0.4265  1.2117 -2.1033  2.809   0.0016  0.6566  0.9206]]


array([2.1933, 1.915 , 3.6849, 4.7084, 1.8538, 2.1502, 6.397 ])

## Table 4.1.4

In [23]:
all_df = {}
for i, d in enumerate(df.items()):
    name, data = d
    all_df[name] = data
all_data = pd.concat(df.values())

In [24]:
all_data = all_data[[ "DEPTH", "DT", "GR", "LLD", "NPHI", "RHOB", "Log_Facies"]]
all_data = all_data.dropna(axis=0, how='any')
data = all_data

In [25]:
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LogisticRegression

In [26]:
X = data[["DEPTH", "DT", "GR", "LLD", "NPHI", "RHOB",]]
ss = StandardScaler()
X = ss.fit_transform(X)
Y = data['Log_Facies'].apply(lambda x: int(x)-1)

In [27]:
clf = LogisticRegression()

In [28]:
clf.fit(X, Y)

/anaconda3/lib/python3.7/site-packages/sklearn/linear_model/logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
/anaconda3/lib/python3.7/site-packages/sklearn/linear_model/logistic.py:460: FutureWarning: Default multi_class will be changed to 'auto' in 0.22. Specify the multi_class option to silence this warning.
  "this warning.", FutureWarning)


LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='warn',
          n_jobs=None, penalty='l2', random_state=None, solver='warn',
          tol=0.0001, verbose=0, warm_start=False)

In [29]:
Y_pred = clf.predict(X)

In [30]:
from sklearn.metrics import confusion_matrix 

In [31]:
#results = confusion_matrix(Y, Y_pred)
#results
#from sklearn.metrics import classification_report
#report = classification_report(Y, Y_pred)
#print(report)

In [32]:
print(clf.intercept_)
print(clf.coef_)

[ 0.78055015 -1.04563358 -4.77313397]
[[ 0.36258517 -0.11776839 -0.0184775  -0.19050506 -2.63032929 -4.02616705]
 [-0.09633896 -0.08903942 -0.23619461 -0.06511261  1.26371285  1.94912398]
 [-0.95162169  0.12162854  1.19518554  0.61236001  0.48844301  1.46698523]]


In [33]:
#Y_binary = data['Log_Facies'].apply(lambda x: 1 if int(x)==1 else 0)
#clf_binary = LogisticRegression()
#clf_binary.fit(X, Y_binary)
#print(clf_binary.intercept_)
#print(clf_binary.coef_)

In [34]:
coef = np.round(clf.coef_, 4)
print(coef)
coef = abs(coef)
coef = np.sum(coef, axis=0)
coef

[[ 0.3626 -0.1178 -0.0185 -0.1905 -2.6303 -4.0262]
 [-0.0963 -0.089  -0.2362 -0.0651  1.2637  1.9491]
 [-0.9516  0.1216  1.1952  0.6124  0.4884  1.467 ]]


array([1.4105, 0.3284, 1.4499, 0.868 , 4.3824, 7.4423])